global using Cherwell.Api.Model.Approval;
global using Cherwell.Api.Model.BusinessObject;
global using Cherwell.Api.Model.Core;
global using Cherwell.Api.Model.Forms;
global using Cherwell.Api.Model.Lifecycle;
global using Cherwell.Api.Model.OneStepActions;
global using Cherwell.Api.Model.Queues;
global using Cherwell.Api.Model.Searches;
global using Cherwell.Api.Model.Security;