/* 
 * Cherwell Rest API
 *
 * <a href=\"https://xantes.sharepoint.com/sites/supporthelp\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 10.5.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// TrebuchetWebApiDataContractsTeamsAddUserToTeamRequest
    /// </summary>
    [DataContract]
    public partial class TrebuchetWebApiDataContractsTeamsAddUserToTeamRequest :  IEquatable<TrebuchetWebApiDataContractsTeamsAddUserToTeamRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TrebuchetWebApiDataContractsTeamsAddUserToTeamRequest" /> class.
        /// </summary>
        /// <param name="TeamId">TeamId.</param>
        /// <param name="UserIsTeamManager">UserIsTeamManager.</param>
        /// <param name="UserRecordId">UserRecordId.</param>
        public TrebuchetWebApiDataContractsTeamsAddUserToTeamRequest(string TeamId = default(string), bool? UserIsTeamManager = default(bool?), string UserRecordId = default(string))
        {
            this.TeamId = TeamId;
            this.UserIsTeamManager = UserIsTeamManager;
            this.UserRecordId = UserRecordId;
        }
        
        /// <summary>
        /// Gets or Sets TeamId
        /// </summary>
        [DataMember(Name="teamId", EmitDefaultValue=false)]
        public string TeamId { get; set; }
        /// <summary>
        /// Gets or Sets UserIsTeamManager
        /// </summary>
        [DataMember(Name="userIsTeamManager", EmitDefaultValue=false)]
        public bool? UserIsTeamManager { get; set; }
        /// <summary>
        /// Gets or Sets UserRecordId
        /// </summary>
        [DataMember(Name="userRecordId", EmitDefaultValue=false)]
        public string UserRecordId { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TrebuchetWebApiDataContractsTeamsAddUserToTeamRequest {\n");
            sb.Append("  TeamId: ").Append(TeamId).Append("\n");
            sb.Append("  UserIsTeamManager: ").Append(UserIsTeamManager).Append("\n");
            sb.Append("  UserRecordId: ").Append(UserRecordId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as TrebuchetWebApiDataContractsTeamsAddUserToTeamRequest);
        }

        /// <summary>
        /// Returns true if TrebuchetWebApiDataContractsTeamsAddUserToTeamRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of TrebuchetWebApiDataContractsTeamsAddUserToTeamRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TrebuchetWebApiDataContractsTeamsAddUserToTeamRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.TeamId == other.TeamId ||
                    this.TeamId != null &&
                    this.TeamId.Equals(other.TeamId)
                ) && 
                (
                    this.UserIsTeamManager == other.UserIsTeamManager ||
                    this.UserIsTeamManager != null &&
                    this.UserIsTeamManager.Equals(other.UserIsTeamManager)
                ) && 
                (
                    this.UserRecordId == other.UserRecordId ||
                    this.UserRecordId != null &&
                    this.UserRecordId.Equals(other.UserRecordId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.TeamId != null)
                    hash = hash * 59 + this.TeamId.GetHashCode();
                if (this.UserIsTeamManager != null)
                    hash = hash * 59 + this.UserIsTeamManager.GetHashCode();
                if (this.UserRecordId != null)
                    hash = hash * 59 + this.UserRecordId.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
